### ISSUE TITLE
Feature Request: Add Options to uninstall apps

### ISSUE THREAD

**Issue by Sesmicwastaken** [ChrisTitusTech/win10script#120]
It would be cool if you add a seperate tab for uninstalling apps you **select** only as it becomes a little bit faster than typing the same command in powershell for uninstalling apps 

:-)

**Comment by Pro-cyber-byte** [comment]
Yeah , would love to have that , considering this is a "Debloat Script" removing the uninstall store apps feature literally just killed the debloat side of it .. it was one of the main reasons I chose this script over Sycnex's script , remove bloat Store apps and disable telemetry  all in the same package , was kinda disappointed to see it get removed .. Would love to have it back :)

**Comment by technocapeman** [comment]
I was thinking the exact same thing. I opened a PR ( #146 ) that adds the debloat functionality. Hopefully, this PR can get merged!

P.S. I know that @ChrisTitusTech mentioned that many people didn't like the fact that many of their apps were being removed, so instead of integrating it into the essential tweaks, I made it a separate button.

**Comment by technocapeman** [comment]
UPDATE: PR #149 has been merged! This project now has the ability to uninstall windows bloatware.

**Comment by Sesmicwastaken** [comment]
> UPDATE: PR #149 has been merged! This project now has the ability to uninstall windows bloatware.

Thanks for all the hard work ❤️
