### ISSUE TITLE
How to make it work on multiple accounts

### ISSUE THREAD

**Issue by BORIKKEN21** [ChrisTitusTech/win10script#15]
Is there a way to make this work on multi accounts? or I have to manually run it through all the accounts on the same PC?

**Comment by gfelipe099** [comment]
Most of the settings are user-only, so you'll need to execute it for each one without admin permissions.  
- To debloat a user, **if the computer is joined into a domain**, run this:  
`Get-AppxPackage | Remove-AppxPackage` instead of `Get-AppxPackage -AllUsers | Remove-AppxPackage`  
or you will get errors.
  
- Or, if you prefer to keep critical functionality, run this other one into each user with no admin rights, which will leave the Windows Store and the NVIDIA Control panel (and all of the required components) untoched:  
`Get-AppxPackage | where-object {$_.name -notlike "*Microsoft.WindowsStore*"} | where-object {$_.name -notlike "*NVIDIACorp.NVIDIAControlPanel*"} | Remove-AppxPackage`

Hope it helps somehow.

**Comment by BORIKKEN21** [comment]
but where is the link to the script in those commands? I only know how to right click the script and run as admin

**Comment by gfelipe099** [comment]
Open a PowerShell console with no admin rights, either by:  
- Searching it on the start menu.
- Pressing Win+R, typing powershell.exe and pressing ENTER. 

Afterwards, copy and paste any of the commands of your choice and then right click on the console window to paste it, then press ENTER to execute it.

**Comment by BORIKKEN21** [comment]
But this commands does not have nothing to do with the script, right?

**Comment by gfelipe099** [comment]
No. But you must run them if the user is on a domain.

**Comment by BORIKKEN21** [comment]
It worked even on a non domain PC, Thanks! Who did developed this? Is there any kind of documentation?

**Comment by gfelipe099** [comment]
It is a fork from many Windows 10 debloating scripts put together. The documentation may be found on the respective projects.
