### ISSUE TITLE
Edge browser is managed by an organization

### ISSUE THREAD

**Issue by papgergo** [ChrisTitusTech/win10script#247]
Search bar wont autofill.
I removed Edge part from the regedit, but its still the same, even after restart. Also running ShutUp10 messes up File explorer and wont open it, but at least I fixed that one.

**Comment by IsuruPradeepa** [comment]
Have the same issue. Did you find a fix??

**Comment by papgergo** [comment]
> Have the same issue. Did you find a fix??

Sadly not

**Comment by embreem** [comment]
Hi, I’m not to savvy on everything. But I use to have that sorta problem and my fix was to make chrome my default and tweaked the settings in chrome it self. Hope that works, it has for me. Sent from Mail for Windows From: papgergoSent: Friday, December 10, 2021 9:54 AMTo: ChrisTitusTech/win10scriptCc: SubscribedSubject: [ChrisTitusTech/win10script] Edge browser is managed by an organization (Issue #247) Search bar wont autofill.I removed Edge part from the regedit, but its still the same, even after restart. Also running ShutUp10 messes up File explorer and wont open it, but at least I fixed that one.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Shaughn-david** [comment]
When the script is executed it changes some policy settings in edge which makes the “Managed by your organization” thing to appear. But Edge isn’t actually managed by an organization

**Comment by embreem** [comment]
I will look into it and see.  Buy it sounds me like you're running a server so I would look at group policies.  I'll look and get back if I find anything.

Powered by Cricket Wireless
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by embreem** [comment]
If the user is then edge is to Sent from Mail for Windows From: Shaughn-davidSent: Thursday, December 16, 2021 12:16 PMTo: ChrisTitusTech/win10scriptCc: Mike Embree; CommentSubject: Re: [ChrisTitusTech/win10script] Edge browser is managed by an organization (Issue #247) When the script is executed it changes some policy settings in edge which makes the “Managed by your organization” thing to appear. But Edge isn’t actually managed by an organization—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by kasai2210** [comment]
Heyy, I know the fix for this, just open the registry editor and navigate to this location - `Computer\HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Edge`

Then just change the value of the attribute you want to enable to `1` from `0`.
Hope this helps you.

**Comment by IsuruPradeepa** [comment]
Thanks kasai2210. Your solution works.
