### ISSUE TITLE
Installing New Powershell version 7.1 

### ISSUE THREAD

**Issue by RiteshChepuri** [ChrisTitusTech/win10script#266]
The new Powershell from the store which is version 7.1 is beginning to attract so many DEVS to install and use as its is giving way more than options than the Windows Powershell version 5.0. So I was thinking it would be great if we include the new powershell in the Debloater

**Comment by DocAElstein** [comment]
@RiteshChepuri
Hello Ritesh Chepuri
Please forgive me if I am asking a dumb or inappropriate question.
I am asking only because I am new to GitHub and so I am trying  to learn how things work here and why and when things are done.

So my question on you is:

Why did you close this issue?

Thanks
Alan Elston
