### ISSUE TITLE
Realtime protection is still enabled after reboot

### ISSUE THREAD

**Issue by sonicmixmaster** [ChrisTitusTech/win10script#74]
![2021-01-11 13_19_48-Windows Security](https://user-images.githubusercontent.com/58009937/104222130-d9305c80-540f-11eb-9b62-5e9afea4fa5c.png)

**Comment by mikhoul** [comment]
If I'm right since the last Windows version  you have to disable manually the tamper protection to be able to change Defender settings  with PS script: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection

Regards :octocat:

**Comment by sonicmixmaster** [comment]
I did that already. I had tamper protection disabled for a long time before
I even attempted this script.

**Comment by ChrisTitusTech** [comment]
There is more things coming down the pipe. I am removing the AV disable and Security sections in next commit. I will revisit this in the future.
