### ISSUE TITLE
Can't install Microsoft Store apps.

### ISSUE THREAD

**Issue by Zupanico** [ChrisTitusTech/win10script#94]
When trying to install a Microsoft Store app, the app will download without any problem but the installation progress bar will reach about 90%, freeze and there will be this error code.

Code: 0x800700B7

**Comment by masninja** [comment]
@Zupanico the problem is when you download apps like Xbox in Microsoft Store or is a problem with Microsoft Store App?

Try this:
Windows Key + S and type services.msc or CTRL + Shift + Esc (Open Task Manager) and them go to Services Tab and click in Go to Services.
Now, check if the Windows Updates is set to Manual (Trigger Start) Running (Some versions could have this set to automatic).
If yes, try to restart the service and see if fix

Another way to try is this
Open CMD as admin and type the following commands
net stop wuauserv
net stop cryptSvc
net stop bits
net stop msiserver
Ren C:\Windows\SoftwareDistribution SoftwareDistribution.old
Ren C:\Windows\System32\catroot2 Catroot2.old
net start wuauserv
net start cryptSvc
net start bits
net start msiserver

and them restart your computer and try again.

Source: https://www.youtube.com/watch?v=Nu1Tqdsh1Mw

**Comment by Brandonbr1** [comment]
> When trying to install a Microsoft Store app, the app will download without any problem but the installation progress bar will reach about 90%, freeze and there will be this error code.
> 
> Code: 0x800700B7

try reinstalling the microsoft store

open powershell in adimin and coppy this command

 Get-AppxPackage -allusers *WindowsStore* | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register “$($_.InstallLocation)\AppXManifest.xml”}


or 

powershell aging in admin amd type the cmd

➤ COMMAND: Get-AppXPackage *WindowsStore* -AllUsers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}

➤ COMMAND #1:
Get-AppXPackage -AllUsers -Name Microsoft.WindowsStore | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml" -Verbose}

➤ COMMAND #2:
Get-AppXPackage | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"} 

➤ COMMAND #3:
PowerShell -ExecutionPolicy Unrestricted -Command "& {$manifest = (Get-AppxPackage Microsoft.WindowsStore).InstallLocation + '\AppxManifest.xml' ; Add-AppxPackage -DisableDevelopmentMode -Register $manifest}"

➤ COMMAND #4:
Get-AppxPackage -allusers Microsoft.WindowsStore | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"} 

that should owrk if not reinstall windows 10

source:[https://www.youtube.com/watch?v=fcDtd52s1pk](https://www.youtube.com/watch?v=fcDtd52s1pk)

**Comment by ChrisTitusTech** [comment]
I'm removing all app removals and MS Store interactions in the next update.
